project:
  type: website
  output-dir: docs
  
website:
  title: "Madison Hess' Personal Webpage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - dashboard.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/madisonrhess/
      - icon: github
        href: https://github.com/madisonhess
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Madison Hess"

format:
  html:
    theme: cerulean
    toc: true

editor: source

